#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [ $BRANCH_NAME != '(no branch)' ]
then
  npx --no-install is-ci || exec < /dev/tty && node_modules/.bin/cz --hook || true
fi
